# Uncomment the next line to define a global platform for your project
platform :ios, '15.6'
target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for iosApp
  #pod 'kSocket', :path => '../kSocket'
  pod 'Socket.IO-Client-Swift', '15.2.0'
end
